version: '3'

services:

  globodns_db:
    image: mysql:5.6
    container_name: globodnsdb.local
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: globodns
    network_mode: "host"
    ports:
      - 3306:3306
    healthcheck:
      test: "(echo >/dev/tcp/localhost/3306) &>/dev/null"

  globodns_master:
    image: tuxmonteiro/globodns.master:20190214
    container_name: globodns.master
    network_mode: "host"
    privileged: true
    ports:
      - 22:22
      - 53:53/udp

  globodns:
    image: tuxmonteiro/globodns:20190214
    container_name: globodns.local
    environment:
      BIND_MASTER_HOST: localhost
      BIND_MASTER_IPADDR: 127.0.0.1
      DB_HOST: 127.0.0.1
      DB_PASSWORD: password
    privileged: true
    depends_on:
      - globodns_db
      - globodns_master
    network_mode: "host"
    ports:
      - 8080:8080

